- hosts: slave1user,slave2user
  user: root
  tasks:

  - name: add slave user
    user: 
      name: slave
      password: slave
      groups: sudo
      state: present


  - name: ensure repository key is installed
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: copy slave code to the master host
    synchronize:
      src: slave_software/
      dest: /home/slave/slave_software/
  
  - name: copy startup code to the master host
    synchronize:
      src: runslave.sh
      dest: /usr/local/bin/
  
  - name: copy startup service to the master host
    synchronize:
      src: startupslave.service
      dest: /etc/systemd/system/


  - name: add the correct rights to the startup file
    shell: sudo chmod 644 /etc/systemd/system/startupslave.service
 
  - name: add the correct rights to the startup file
    shell: sudo chmod 744 /usr/local/bin/runslave.sh

  - name: reload deamon
    shell: sudo systemctl daemon-reload

  - name: enable startup service
    shell: sudo systemctl enable startupslave.service

  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes

  - name: install python3
    apt: name=python3 state=present

  - name: install python3-pip
    apt: name=python3-pip state=present

  - name: install ufw
    apt: name=ufw state=present

  - name: change directory to /home/slave/slave_software
    shell: cd /home/slave/slave_software

  - name: install requirements
    shell: pip3 install -r /home/slave/slave_software/requirements.txt

  - ufw:
     state: enabled
     policy: deny

  - ufw:
     logging: on

  - ufw:
     rule: allow
     port: 8000
     proto: tcp
  - ufw:
     rule: allow
     port: 22
     proto: tcp

  - name: Log into DockerHub
    docker_login:
      username: argusproof
      password: DeltaTeam

  - name: Pull the latest images from private repository on DockerHub
    shell: cd /home/slave/slave_software && docker image pull --all-tags argusproof/argusproof_deltateam
  
  - name: Unconditionally reboot the machine with all defaults
    reboot:
#/***************************************************************
#*
#* Copyright (Wouter Weemaes, Safi Bouziane, Kamil Grielens, Robbe Willeme) - All rights reserved. 
#*
#* Unauthorized use, copy, modify, merge, publish, distribute, sublicense, 
#* and/or sell any parts of the software/source code is strictly prohibited.
#* Proprietary and confidential
#* License: No license. 
#* Written by: (Wouter Weemaes) (wouterweemaes@outlook.com), (06/2022)
#*
#****************************************************************/
