- hosts: mac
  user: root
  tasks:
  - name: ensure repository key is installed
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: copy src.txt as dest.txt in the same dir 
    copy:
      src: slave_software/
      dest: /home/slave/slave_software/

  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes

  - name: install python3
    apt: name=python3 state=present

  - name: install python3-pip
    apt: name=python3-pip state=present

  - name: install ufw
    apt: name=ufw state=present

  - name: change directory to /home/slave_software
    shell: cd /home/slave/slave_software

  - name: install requirements
    shell: pip3 install -r /home/slave_software/requirements.txt

  - ufw:
     state: enabled
     policy: deny

  - ufw:
     logging: on

  - ufw:
     rule: allow
     port: 8000
     proto: tcp

  - ufw:
     rule: allow
     port: 22
     proto: tcp

  - name: Setup alternate SSH port
    lineinfile:
     dest: "/etc/ssh/sshd_config"
     regexp: "^Port"
     line: "Port 2222"

  - name: add slave user
    user: 
      name: slave
      password: slave
      groups: sudo
      state: present

  - name: Log into DockerHub using a custom config file
    docker_login:
      username: argusproof
      password: DeltaTeam
      config_path: /tmp/.mydockercfg

  - name: Pull the latest images from private repository on DockerHub
    shell: docker image pull --all-tags argusproof/argusproof_deltateam

  - name: run uvicorn
    shell: cd /home/slave/slave_software && uvicorn mainapi:app --host 0.0.0.0 --port 8000


    