- hosts: slave1,slave2
  user: root
  tasks:
  - name: ensure repository key is installed
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: copy slave code to the slave host
    copy:
      src: slave_software/
      dest: /home/{{ansible_user}}/slave_software/

  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes

  - name: install python3
    apt: name=python3 state=present

  - name: install python3-pip
    apt: name=python3-pip state=present

  - name: install ufw
    apt: name=ufw state=present

  - name: change directory to /home/slave/slave_software
    shell: cd /home/{{ansible_user}}/slave_software

  - name: install requirements
    shell: pip3 install -r /home/{{ansible_user}}/slave_software/requirements.txt

  - ufw:
     state: enabled
     policy: deny

  - ufw:
     logging: on

  - ufw:
     rule: allow
     port: 8000
     proto: tcp
  - ufw:
     rule: allow
     port: 22
     proto: tcp

  - name: add slave user
    user: 
      name: slave
      password: slave
      groups: sudo
      state: present


  - name: Log into DockerHub
    docker_login:
      username: argusproof
      password: DeltaTeam

 - name: rebuild test1 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test1 -f dockerfile.http . && docker tag test1:latest argusproof/argusproof_deltateam:test1 && docker push argusproof/argusproof_deltateam:test1
  - name: rebuild test2 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test2 -f dockerfile.geoip . && docker tag test2:latest argusproof/argusproof_deltateam:test2 && docker push argusproof/argusproof_deltateam:test2
  - name: rebuild test3 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test3 -f dockerfile.bl . && docker tag test3:latest argusproof/argusproof_deltateam:test3 && docker push argusproof/argusproof_deltateam:test3
  - name: rebuild test4 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test4 -f dockerfile.ssl . && docker tag test4:latest argusproof/argusproof_deltateam:test4 && docker push argusproof/argusproof_deltateam:test4
  - name: rebuild test5 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test5 -f dockerfile.dnssec . && docker tag test5:latest argusproof/argusproof_deltateam:test5 && docker push argusproof/argusproof_deltateam:test5
  - name: rebuild test6 with latest github changes
    shell: cd /home/{{ansible_user}}/master_software/QueueHandler/ && docker build -t test6 -f dockerfile.ipv6 . && docker tag test6:latest argusproof/argusproof_deltateam:test6 && docker push argusproof/argusproof_deltateam:test6

  - name: run uvicorn
    shell: cd /home/{{ansible_user}}/slave_software && uvicorn mainapi:app --host 0.0.0.0 --port 8000
    async: 45
    poll: 0
