FROM python:latest
#vr blacklist
RUN pip3 install git+https://github.com/rthalley/dnspython
RUN pip3 install urllib3
RUN pip3 install requests
run pip3 install mysql-connector-python
COPY blacklistcheck.py ./